complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-1
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-96
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highmem-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highmem-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highmem-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highmem-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highmem-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highmem-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highmem-96
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highcpu-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highcpu-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highcpu-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highcpu-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highcpu-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highcpu-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-highcpu-96
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-48
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-80
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-96
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-128
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highcpu-224
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-48
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-80
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-highmem-96
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-48
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-80
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-96
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-128
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2d-standard-224
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-48
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highcpu-80
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-48
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-highmem-80
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-32
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-48
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-64
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n2-standard-80
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highcpu-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highcpu-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highcpu-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highcpu-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highmem-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highmem-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highmem-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-highmem-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-standard-2
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-standard-4
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-standard-8
complete -c gcp-machines -f -n "__fish_use_subcommand" -a e2-standard-16
complete -c gcp-machines -f -n "__fish_use_subcommand" -a n1-standard-1
